title: Link JavaScript files to HTML page
hero_image: images/banner.png
description: Link JavaScript files to HTML page
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Link JavaScript files
