title: JavaScript-bestanden koppelen aan een HTML-pagina
hero_image: images/banner.png
description: JavaScript-bestanden koppelen aan een HTML-pagina
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: JavaScript-bestanden koppelen
