---
title: Lier des fichiers JavaScript à une page HTML
hero_image: images/banner.png
description: Lie des fichiers JavaScript à une page HTML
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Lier des fichiers JavaScript
